#!/usr/bin/env php
<?php
if(!chdir("/usr/aigis")){
	fwrite(STDERR, "Couldn't load files on /usr/aigis.");
	die(1);
}

// Set time zone and error reporting.
date_default_timezone_set("GMT");
error_reporting(E_ALL ^ E_STRICT);

// Include core functions.
include_once "functions.php";
include_once "AigisIRC.php";

try{

	if(!isset($argv[1]))
		throw new Exception("No network specified.");
	$network = $argv[1];
	if(!file_exists(getenv("HOME")."/.config/aigis/aigis.conf")){
		if(file_exists("config/aigis.conf"))
			$configF = parse_ini_file("config/aigis.conf", true);
		else throw new Exception("Config file not found.");
	}else $configF = parse_ini_file(getenv("HOME")."/.config/aigis/aigis.conf", true);

	if(!isset($configF[$network]))
		throw new Exception("Unknown network: $network");

	$config = array_merge($configF['Global'], $configF[$network]);
	$config['network'] = $network;
}catch(Exception $e){
	fwrite(STDERR, $e->getMessage()."\n");
	die(1);
}

$AigisIRC = new AigisIRC($config['nick'], $config['network'], $config['altNick']);

// Set connection info and plugin manager.
$ConnIRC = $AigisIRC->setConnInfo($config['serverHost'], $config['serverPort']);
$PlugIRC = $AigisIRC->getAigisVar("PlugIRC");

// NickServ
if(isset($config['ConnIRC_NickServ']))
	$AigisIRC->setAigisVar("nsPass", $config['ConnIRC_NickServ']);
// Load plugins
$PlugIRC->setPrefix($config['PlugIRC_defaultPrefixes']);
foreach($config['PlugIRC_plugins'] as $plugin){
	$PlugIRC->loadPlugin($plugin);
}
$PlugIRC->pluginSendAll("AigisStart", time());

// Set autojoin information.
if(isset($config['autoJoin'])){
	$AigisIRC->autoJoin($config['autoJoin']);
	$AigisIRC->setAigisVar("ajList", $config['autoJoin']);
}

$ConnIRC->connect();

while(true){
	$AigisIRC->loopCycle();
}
