#!/usr/bin/env php
<?php
if(!chdir(realpath(dirname(__FILE__)))){
	fwrite(STDERR, "Couldn't load files on ".realpath(dirname(__FILE__)));
	die(1);
}

// Set time zone and error reporting.
date_default_timezone_set("GMT");
error_reporting(E_ALL ^ E_STRICT);

// Include core functions.
include_once "functions.php";
include_once "AigisIRC.php";

try{

	if(!isset($argv[1]))
		throw new Exception("No network specified.");
	$config = AigisIRC::getConfig($argv[1]);

}catch(Exception $e){
	fwrite(STDERR, $e->getMessage()."\n");
	die(1);
}

$AigisIRC = new AigisIRC($config['nick'], $config['network'], $config['altNick']);

// Set connection info and plugin manager.
$ConnIRC = $AigisIRC->setConnInfo($config['serverHost'], $config['serverPort']);
$PlugIRC = $AigisIRC->getAigisVar("PlugIRC");

// NickServ
if(isset($config['ConnIRC_NickServ']))
	$AigisIRC->setAigisVar("nsPass", $config['ConnIRC_NickServ']);
// Load plugins
$PlugIRC->setPrefix($config['PlugIRC_defaultPrefixes']);
foreach($config['PlugIRC_plugins'] as $plugin){
	$PlugIRC->loadPlugin($plugin);
}
$PlugIRC->pluginSendAll("AigisStart", time());
$ConnIRC->connect();

while(true){
	$AigisIRC->loopCycle();
}
